server:
  port: 8888
  #  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://47.102.143.25:3306/jpademo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true
    username: root
    password: chenLibrary
    # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 5
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 5
      filters: stat
      connection-properties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      connection-init-sqls: set names utf8mb4
  jpa:
    show-sql: true
    # 没有表就创建
    generate-ddl: true
    hibernate:
      ddl-auto: none
    open-in-view: true

  redis:
    host: 47.102.143.25
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-active: 4
